services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 886264       # 设置root用户密码
      MYSQL_USER: jiayue                # 创建的普通用户
      MYSQL_PASSWORD: 886364            # 普通用户密码
    ports:
      - "3306:3306"                     # 将容器的3306端口映射到主机
    volumes:
      - ~/.local/share/mysql:/var/lib/mysql       # 数据库数据持久化
    networks:
      - mysql_network

volumes:
  mysql_data:                           # 定义持久化卷

networks:
  mysql_network:                        # 定义网络
